### ISSUE TITLE
this.cropper.imgReset(); 图片位置

### ISSUE THREAD

**Issue by tunghsingw** [wx-plugin/image-cropper#12]
按照文档的使用，在bindimageload响应函数中调用this.cropper.imgReset()后，图片相对裁剪员和整个屏幕总是下降一小块。
![image](https://user-images.githubusercontent.com/22024979/54409899-13e9e080-4724-11e9-9102-58bca2a54cbb.png)

**Comment by 1977474741** [comment]
找到原因了吗？什么手机？看看代码

**Comment by 1977474741** [comment]
问题已修复

**Comment by 18713419413** [comment]
你好  我也出现这个问题了  我拉取的是最新的代码  但是还有这个问题  是因为我自定义了 裁剪框的宽高吗
