### ISSUE TITLE
文档建议

### ISSUE THREAD

**Issue by tunghsingw** [wx-plugin/image-cropper#13]
文档中几个位置似乎有些问题
1、
"usingComponents": {
        "navigationBarTitleText": "裁剪图片",
        "image-cropper": "../image-cropper/image-cropper",
        "disableScroll": true,
    }
正确应该为：
"navigationBarTitleText": "裁剪图片",
"disableScroll": true,
"usingComponents": {
        "image-cropper": "../image-cropper/image-cropper"
 }

2、
wxss文件末尾中的@import '../image-cropper/image-cropper.wxss'似乎没有必要。

**Comment by 1977474741** [comment]
谢谢指正，刚发现，那两个属性不应该放usingComponents里。文件末尾我记得之前放前面会报错来着

**Comment by tunghsingw** [comment]
在业务代码似乎没有必要引用组件内的样式@import '../image-cropper/image-cropper.wxss'

**Comment by 1977474741** [comment]
还真的是
