### ISSUE TITLE
有时候会发生如下问题 

### ISSUE THREAD

**Issue by chengshihard** [wx-plugin/image-cropper#2]
![wechatimg32](https://user-images.githubusercontent.com/13564095/50733078-8210a500-11c1-11e9-8303-7e64cb4ea4d4.jpeg)

**Comment by 1977474741** [comment]
你是说刚进来的时候吗

**Comment by chengshihard** [comment]
是的

**Comment by 1977474741** [comment]
好的👌，下个版本修复

**Comment by 1977474741** [comment]
已经修复了
