### ISSUE TITLE
导致小程序变卡、微信崩溃重启

### ISSUE THREAD

**Issue by chenweiyang1** [wx-plugin/image-cropper#25]
我在uni-app中使用了该插件后在手机端预览发现小程序卡死  微信崩溃重启

**Comment by 1977474741** [comment]
暂时没对uni-app做兼容，纯微信小程序组件格式写的。pc端就正常吗？android还是ios

**Comment by chenweiyang1** [comment]
> 暂时没对uni-app做兼容，纯微信小程序组件格式写的。pc端就正常吗？android还是ios
开发者工具上正常的，预览的时候会出现这种问题，  裁剪上传完成后销毁裁剪对象就不会影响使用， 我暂时是这样解决的。

**Comment by 1977474741** [comment]
如果裁剪组件是在一个单独的页面，裁剪完关掉，就不会出现这个问题。如果和业务页面在一起，裁剪完就销毁。

**Comment by 1977474741** [comment]
还在吗

**Comment by chenweiyang1** [comment]
在的

**Comment by 1977474741** [comment]
能加下我qq吗？1977474741

**Comment by 1977474741** [comment]
把插件放在static文件夹里，裁剪完成需要销毁裁剪对象
