### ISSUE TITLE
加个按钮旋转90度，然后图片锁定

### ISSUE THREAD

**Issue by QQ123215754** [wx-plugin/image-cropper#3]
怎么调成旋转90度然后锁定边框？

**Comment by 1977474741** [comment]
旋转90之后限制图片移动范围，一直保持在90度是吗？

**Comment by QQ123215754** [comment]
就是按钮按一下就旋转90℃，然后让图片不出参考框

**Comment by 1977474741** [comment]
this.setData({
  angle:90
})
给组件标签加上angle属性，直接setData就可以，但在限制模式下，图片只能在0度。

**Comment by 1977474741** [comment]
这个需求好像挺常见的，下个版本我加上

**Comment by 1977474741** [comment]
已经更新了，可以用了

**Comment by QQ123215754** [comment]
好的，多谢。
