### ISSUE TITLE
控制整个组件的长宽

### ISSUE THREAD

**Issue by zjldwb** [wx-plugin/image-cropper#32]
对应工具或者iOS或者Andriod的版本号  无

微信版本号  无

代码截图  无

重现步骤  

期待的行为

实际的行为 想要改变整个区域的大小，应该怎样控制

**Comment by 1977474741** [comment]
触摸区域吗

**Comment by zjldwb** [comment]
相当于是触摸区，现在这个插件dome 都是全屏显示的，我要2/3屏显示，且保持触摸区不会有问题------------------ 原始邮件 ------------------
发件人: "鹅鹅鹅"<notifications@github.com>
发送时间: 2019年4月29日(星期一) 晚上6:49
收件人: "wx-plugin/image-cropper"<image-cropper@noreply.github.com>;
抄送: "zjldwb"<936334513@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wx-plugin/image-cropper] 控制整个组件的长宽 (#32)



触&#x6478;区域吗
 
&mdash;

**Comment by 1977474741** [comment]
你可以把那1/3的z-index设的高一些，需要的话把裁剪框默认居中的位置改一下

**Comment by zjldwb** [comment]
这样子裁剪框也能跑到那1/3中，且图片就不相对于2/3那部分剧中------------------ 原始邮件 ------------------
发件人: "鹅鹅鹅"<notifications@github.com>
发送时间: 2019年4月29日(星期一) 晚上7:04
收件人: "wx-plugin/image-cropper"<image-cropper@noreply.github.com>;
抄送: "zjldwb"<936334513@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wx-plugin/image-cropper] 控制整个组件的长宽 (#32)



你可以把那1/3的z-index设的高一些，需要的话把裁剪框默认居中的位置改一下
 
&mdash;

**Comment by 1977474741** [comment]
把裁剪框默认居中的位置改一下，你看下源码，imgCenter和cutCenter函数

**Comment by zjldwb** [comment]
没有imgCenter这个字段


 
---原始邮件---
发件人: "鹅鹅鹅"<notifications@github.com>
发送时间: 2019年4月30日(星期二) 中午1:22
收件人: "wx-plugin/image-cropper"<image-cropper@noreply.github.com>;
抄送: "zjldwb"<936334513@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wx-plugin/image-cropper] 控制整个组件的长宽 (#32)



把裁剪框默认居中的位置改一下，你看下源码，imgCenter和cutCenter函数
