### ISSUE TITLE
图片与裁剪框的位置

### ISSUE THREAD

**Issue by 18713419413** [wx-plugin/image-cropper#35]
进入裁剪页面后裁剪框和图片不居中  过一会才会自动居中  但是图片还是会有一部分在裁剪框外面  就是 裁剪框上面会有一部分空白  只有手动移动后 才可以

**Comment by 18713419413** [comment]
> 进入裁剪页面后裁剪框和图片不居中 过一会才会自动居中 但是图片还是会有一部分在裁剪框外面 就是 裁剪框上面会有一部分空白 只有手动移动后 才可以   对了  我是自定义宽高的

**Comment by 1977474741** [comment]
demo放进去就这样吗

**Comment by eagowang** [comment]
我也有这个问题，不过安卓没问题，只有ios才有

**Comment by eagowang** [comment]
> 我也有这个问题，不过安卓没问题，只有ios才有

在调用插件时，手动调一次this.cropper.imgReset()。安卓和ios都可以了
