### ISSUE TITLE
在wepy中有没有办法使用

### ISSUE THREAD

**Issue by nicksun011** [wx-plugin/image-cropper#38]
对应工具或者iOS或者Andriod的版本号

微信版本号

代码截图

重现步骤

期待的行为

实际的行为

**Comment by 1977474741** [comment]
没了解过这个框架，不过既然只是小程序框架，肯定是可以的，你看一下如何引入小程序原生组件。

**Comment by nicksun011** [comment]
引入进wepy框架创建的工程中，非常卡，基本不可用

**Comment by 1977474741** [comment]
console、调试模式、真机调试确认都没开启吗

**Comment by nicksun011** [comment]
对的，在模拟器下看也有卡顿，不过还能用。真机上体验版本的时候就不行了

**Comment by 1977474741** [comment]
不用wepy的话卡吗

**Comment by nicksun011** [comment]
不用wepy的我试了不卡，效率很好

**Comment by nicksun011** [comment]
请问这个有办法解决么

**Comment by 1977474741** [comment]
你排查下看是什么原因

**Comment by nicksun011** [comment]
真机上imageLoad被多次触发

**Comment by vFire** [comment]
强烈求解决方法。。。比较了几个，这个性能很好，而且貌似没有直接用canvas原生组件，可定制化成都高。

**Comment by FullOfVigour** [comment]
我在wepy组件中作为自定义组件在.wpy文件中进行引用，可以用，但是会有个问题：初始的裁剪框位置不是居中而是在右下角，请问这个有什么解决方法吗？

**Comment by FullOfVigour** [comment]
通过wpy文件引用：
![image](https://user-images.githubusercontent.com/25943199/60648319-4e61bf80-9e72-11e9-803e-b9a098833278.png)
正常原生引用：
![image](https://user-images.githubusercontent.com/25943199/60648360-60dbf900-9e72-11e9-86aa-3f317de22d11.png)
两种写法只是引用的文件不一样，其他都是相同的

**Comment by NBSeven** [comment]
megalo框架里面也是imageload 触发多次

**Comment by 1977474741** [comment]
> 通过wpy文件引用：
> ![image](https://user-images.githubusercontent.com/25943199/60648319-4e61bf80-9e72-11e9-803e-b9a098833278.png)
> 正常原生引用：
> ![image](https://user-images.githubusercontent.com/25943199/60648360-60dbf900-9e72-11e9-86aa-3f317de22d11.png)
> 两种写法只是引用的文件不一样，其他都是相同的

初始化的时候调用imgReset试试
