### ISSUE TITLE
能把图片上传让渡给开发者自己处理？

### ISSUE THREAD

**Issue by XdyGoGo** [wx-plugin/image-cropper#45]
能把图片上传让渡给开发者自己处理？

**Comment by XdyGoGo** [comment]
看了源码 发现上传接口只能调用组件的上传方法 没有让开发者自定义上传（我只想得到裁剪后的图片，其他行为我自己来，我这边需要做上传图片多张，虽然不是一次性，是一张张上传）

**Comment by 1977474741** [comment]
给imgSrc赋值就好了
