### ISSUE TITLE
我原图是jpg,裁剪过后返回png，

### ISSUE THREAD

**Issue by xyy7260** [wx-plugin/image-cropper#49]
对应工具或者iOS或者Andriod的版本号
小程序开发工具
期待的行为
如果我的照片是jpg，那么我裁剪过后的照片也是jpg。而不是返回png撒

**Comment by 1977474741** [comment]
改下310行的输出图片格式

**Comment by xyy7260** [comment]
@1977474741

**Comment by xyy7260** [comment]
@1977474741  谢谢
