### ISSUE TITLE
裁剪横屏照片长度会被压缩，造成比例失调

### ISSUE THREAD

**Issue by thinkmoon** [wx-plugin/image-cropper#52]
对应工具或者iOS或者Andriod的版本号
> 全平台

代码截图
![image](https://user-images.githubusercontent.com/28600813/62435380-82c8e400-b76e-11e9-9c2a-e8c8f144848c.png)

期待的行为
> 显示的比例如下
![image](https://user-images.githubusercontent.com/28600813/62435411-a2f8a300-b76e-11e9-85d4-10095cbb22cd.png)

实际的行为
>实际裁剪效果如下
![image](https://user-images.githubusercontent.com/28600813/62435430-bc015400-b76e-11e9-9be4-d26d32d10a87.png)

图片长宽比与原图不一致。

**Comment by 1977474741** [comment]
你确定没手动设置图片长宽吗？
