### ISSUE TITLE
新增重新选择图片方法

### ISSUE THREAD

**Issue by cn-zx** [wx-plugin/image-cropper#53]
场景：打开图片后发现不想裁剪这张图片，要裁剪另外一张图片，此时只能回到上一个界面，在进来选择图片

自己初步实现：新增按钮 将imgSrc 置为空，并调用组件里面的 _click 方法
实现代码 
![WX20190808-091521](https://user-images.githubusercontent.com/29486720/62668160-5951c780-b9bd-11e9-9b2c-82fa365a0480.png)

表现：能再选择图片，但是选择完成后 界面假死，并报错

报错信息：
![WX20190808-091502](https://user-images.githubusercontent.com/29486720/62668085-1b54a380-b9bd-11e9-8550-e73791f96564.png)

还需要清除哪些值 或重置那个方法？

**Comment by 1977474741** [comment]
给imgSrc赋值就好了
