### ISSUE TITLE
真机模拟和预览效果不一致

### ISSUE THREAD

**Issue by forscherzhang** [wx-plugin/image-cropper#55]
首先感谢作者的付出。
在学习作者的demo时，使用真机模拟和预览两种模式裁剪效果出现差异，在真机模拟中效果正常，但是通过预览模式，只会裁剪选中区域的左上角。测试使用的系统为ios12.4 微信版本7.0.5。

**Comment by 1977474741** [comment]
基础库版本用最高的试一试
