### ISSUE TITLE
点击裁剪框的预览效果 怎么转移到按钮上

### ISSUE THREAD

**Issue by 1362300682** [wx-plugin/image-cropper#8]
![image](https://user-images.githubusercontent.com/18088179/53870365-1322c180-4035-11e9-9bf2-c8d738f04795.png)

**Comment by 1977474741** [comment]
this.cropper = this.selectComponent("#image-cropper");
this.cropper.getImg(function(obj){
   
})

**Comment by 1362300682** [comment]
好的，谢谢
