### ISSUE TITLE
设置了裁剪框居中对齐，图片向下了，怎么设置图片图片和裁剪框对齐

### ISSUE THREAD

**Issue by AuYuHui** [wx-plugin/image-cropper#82]
.image-cropper .main {
  position: absolute;
  width: 100vw;
  height: calc(100% - 180rpx);
  overflow: hidden;
  display: flex;
  align-items: center;
  justify-content: center;
}
  display: flex;
  align-items: center;
  justify-content: center;
css 中加了这段 居中

**Comment by 1977474741** [comment]
默认居中，不支持改裁剪框位置，强制改css是不行的
