### ISSUE TITLE
使用getImg获取图片错误

### ISSUE THREAD

**Issue by 958627869** [wx-plugin/image-cropper#9]
给按钮绑定getImg获取结果图片，提示getCallback is not a function。请问是什么问题

**Comment by 1977474741** [comment]
传入的是个函数吗

**Comment by 958627869** [comment]
那getImg()应该怎么传参呢

**Comment by 1977474741** [comment]
this.cropper = this.selectComponent("#image-cropper");
this.cropper.getImg(function(obj){

})

**Comment by 958627869** [comment]
嗯嗯，谢谢耐心指导，另外一个问题this.cropper.setTransform(90);点击旋转，没效果是参数有问题？想实现每点击一次转90度

**Comment by 1977474741** [comment]
自己看看文档
